"""ReviewLink migration

Revision ID: 589da65acd39
Revises: 1540bfc4ce9a
Create Date: 2022-06-25 17:17:10.986835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589da65acd39'
down_revision = '1540bfc4ce9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_links')
    # ### end Alembic commands ###
