"""Review migration

Revision ID: 2499b537799e
Revises: b823709daa10
Create Date: 2022-06-25 16:43:44.373216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2499b537799e'
down_revision = 'b823709daa10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('food_rating', sa.Integer(), nullable=False),
    sa.Column('service_rating', sa.Integer(), nullable=False),
    sa.Column('ambience_rating', sa.Integer(), nullable=False),
    sa.Column('value_rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.String(length=600), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
